[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lindblad"
authors = [{name = "Wiener", email = "tobias.wiener@physik.uni-augsburg.de"}]
dynamic = ["version", "description"]
